-- MySQL Script generated by MySQL Workbench
-- Wed Mar 12 21:26:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestor_proyect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestor_proyect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor_proyect` DEFAULT CHARACTER SET utf8 ;
USE `gestor_proyect` ;

-- -----------------------------------------------------
-- Table `gestor_proyect`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_proyect`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `n_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_proyect`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_proyect`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `n_usuario` VARCHAR(45) NOT NULL,
  `a_p` VARCHAR(45) NOT NULL,
  `a_m` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_roles_idx` (`id_rol` ASC),
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_rol`)
    REFERENCES `gestor_proyect`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_proyect`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_proyect`.`proyectos` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `n_proyecto` VARCHAR(60) NOT NULL,
  `objetivos` VARCHAR(85) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `observaciones` VARCHAR(85) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`),
  INDEX `fk_proyectos_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_proyectos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gestor_proyect`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_proyect`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_proyect`.`equipos` (
  `id_equipo` INT UNSIGNED NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `estado_equipo` ENUM('Activo', 'Inactivo') NOT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_equipo`),
  INDEX `fk_equipos_proyectos1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_equipos_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `gestor_proyect`.`proyectos` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_proyect`.`detalle_equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_proyect`.`detalle_equipos` (
  `id_detalle_equipo` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_equipo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_detalle_equipo`),
  INDEX `fk_detalle_equipos_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_detalle_equipos_equipos1_idx` (`id_equipo` ASC),
  CONSTRAINT `fk_detalle_equipos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gestor_proyect`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_equipos_equipos1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `gestor_proyect`.`equipos` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_proyect`.`actividades_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_proyect`.`actividades_proyecto` (
  `id_actividad_proyecto` INT NOT NULL AUTO_INCREMENT,
  `n_actividad` VARCHAR(65) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `horas_estimadas` INT NOT NULL,
  `horas_utilizadas` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_actividad_proyecto`),
  INDEX `fk_actividades_proyecto_proyectos1_idx` (`id_proyecto` ASC),
  INDEX `fk_actividades_proyecto_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_actividades_proyecto_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `gestor_proyect`.`proyectos` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_proyecto_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `gestor_proyect`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
